### ISSUE TITLE
SNI Support

### ISSUE THREAD

**Issue by diclophis** [cotag/ruby-tls#4]
What is the current state / planned support for SSL SNI?

https://en.wikipedia.org/wiki/Server_Name_Indication

**Comment by stakach** [comment]
I'll add it today. Client support is super easy - do you have any need for server side support?

**Comment by diclophis** [comment]
Thanks for the quick reply... actually the server side support is the more specific requirement that I have... its for this project: https://github.com/mavenlink/bespoked

**Comment by stakach** [comment]
Cool cool - interesting looking project! I'll update the library over the weekend.

**Comment by stakach** [comment]
Let me know what you think about the API - I have set it up something like this:
 
1. create the SSL connection with an initial hostname and certificates
2. add/remove additional hosts

The spec describes the usage:
https://github.com/cotag/ruby-tls/blob/master/spec/verify_spec.rb#L201

I'll expose the object in Libuv too

**Comment by diclophis** [comment]
Awesome, let me get this plugged in and scope it out, many thanks

**Comment by stakach** [comment]
OK so just updated Libuv

```ruby
server = reactor.tcp
server.bind('0.0.0.0', 3000, **{
    private_key: '/blah.key',
    cert_chain: '/blah.crt',
    host_name: 'somehost.com',
    hosts: [{
        private_key: '/blah2.key',
        cert_chain: '/blah2.crt',
        host_name: 'somehost2.com'
    },
    {
        private_key: '/blah3.key',
        cert_chain: '/blah3.crt',
        host_name: 'somehost3.com'
    }]
}) do |client|
    client.start_tls
    client.start_read
end
```

just cutting a new libuv release now

**Comment by diclophis** [comment]
and, is it possible to change the dictionary of hostnames to => private/key/certs after binding?

This is important for my use case of a kubernetes controller, given that over the duration of the controllers runtime it might add/remove several different hosts with different keys/certs

**Comment by stakach** [comment]
New gem cut: `libuv -v 3.1.4`

**Comment by stakach** [comment]
I edited the comment above to describe how to update the hostnames map. add_host and remove_host

**Comment by stakach** [comment]
You don't have to specify any hosts at binding time either. I was just outlining the settings

**Comment by diclophis** [comment]
So freaking awesome
